apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s7ysh8zlu-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/s7ysh8zlu-java-springboot-gitops